### ISSUE TITLE
router v3 support

### ISSUE THREAD

**Issue by travi** [gvaldambrini/storybook-router#1]
great work with the plugin. i've really found it helpful in projects where i can use router v4.

however, i still maintain several projects that are not able to update to v4 yet. i'd love to be able to use this with those projects.

any chance you'd be open to adding support for router v3?

**Comment by gvaldambrini** [comment]
Hi, as react-router v3 is still used in many of the most used react-boilerplates I think it makes sense.  I'm currently playing with router v3 to see how complicated can be supporting both versions without forking the package.

**Comment by gvaldambrini** [comment]
react-router v3 is now supported and the documentation updated. For any suggestion or bug report please open a separate issue.

**Comment by travi** [comment]
thanks a ton for supporting v3! i havent tried out the link-to functionality yet, but even the simple action-logger behavior is a huge help. great work!

**Comment by gvaldambrini** [comment]
👍  let me know if you find any problems

**Comment by chengyin** [comment]
Seems like v3 support is later removed? Is there an earlier version we could use for v3? Thank you.

**Comment by gvaldambrini** [comment]
@chengyin yes, the current version of the package storybook-react-router only supports the v4. You can use the old npm package [storybook-router](https://www.npmjs.com/package/storybook-router). Try first with the last version (0.3.4) and if it doesn't work you should be able to use the 0.2.9.
