### ISSUE TITLE
location did not match any routes

### ISSUE THREAD

**Issue by travi** [gvaldambrini/storybook-router#10]
i expect that this is user error, but i'm struggling to find my problem, so i'm hoping you have something that you can point me to.

i'm using this with react-router v3 and passing my `linkTo` definitions as the first argument to the `storyRouter` decorator as 
```js
.addDecorator(storyRouter({
    '/companies': linkTo('Organisms/Companies List', 'default')
  }))
```

however, when i click on the `<Link>` that points to `/companies` i get the following error:
```
Warning: [react-router] Location "/companies" did not match any routes
```

this then results in the following trace:
```
Uncaught TypeError: Cannot read property 'emit' of null
    at Object.eval [as /companies] (preview.js?e884:22)
    at HistoryWatcher.onHistoryChanged (StoryRouter.js?b7c2:202)
    at eval (useQueries.js?c2b7:75)
    at eval (useBasename.js?bfcd:67)
    at eval (createHistory.js?96f2:55)
    at Array.forEach (<anonymous>)
    at updateLocation (createHistory.js?96f2:54)
    at eval (createHistory.js?96f2:117)
    at eval (createHistory.js?96f2:90)
    at next (AsyncUtils.js?f52d:51)
```

my assumption is that the "did not match any routes" error shouldn't occur since i defined that route in the decorator? should i be configuring that in a different way?

i'm using `v0.2.9` of `storybook-router`

**Comment by travi** [comment]
i tried configuring similar routes in a public project and am able to reproduce the same problem.

* clone https://github.com/travi/admin.travi.org-components
* checkout the `storybook-router` branch
* npm i 
* npm start
* navigate to `Resource List` -> `rides list` or `users list`
* click on any of the list items to see the errors

my routes are configured at https://github.com/travi/admin.travi.org-components/blob/storybook-router/stories/resource-list.js#L17-L20

hopefully you can spot the details that i'm missing

**Comment by gvaldambrini** [comment]
thank you for the report, I'll have a look asap.

**Comment by gvaldambrini** [comment]
After investigating a bit, I am now quite sure that the problem is not related to `StoryRouter`. The problem is that (for an unknown reason) `linkTo` is not working with your repo. This is an updated `errors.js` that is not using at all `StoryRouter` but still does not work:
```
import React from 'react';
import {storiesOf} from '../.storybook/facade-storybook';
import {linkTo} from '@storybook/addon-links';
import NotFound from '../src/errors/not-found';
import ServerError from '../src/errors/server-error';

storiesOf('Errors', module)
  .add('not found', () => <NotFound />)
  .add('server error', () => <ServerError />)
  .add('home', () => (
      <div onClick={linkTo('Errors', 'not found')}>
        CLICK ME
      </div>
    ));
```
Probably there is something in your configuration (maybe another addon?) that makes `linkTo` not working. Hope this help.

**Comment by travi** [comment]
thank you so much for investigating. since you confirmed that `linkTo` itself was not working, i realized that i had forgotten to register it in `.storybook/addons.js`.

such a simple mistake that i'm sorry i distracted you with the problem. thank you again for investigating and thank you for such a useful addon!
