### ISSUE TITLE
$attrs is readonly?

### ISSUE THREAD

**Issue by dweldon** [gvaldambrini/storybook-router#13]
I'm using Vue, and whenever I click on a link everything behaves normally but I get the following errors in the console:

* `$attrs is readonly`
* `$listeners is readonly`

Any ideas?

**Comment by gvaldambrini** [comment]
The [example project](https://github.com/gvaldambrini/storybook-router/tree/master/examples/vue-router) seems to not have this issue. Could you check the differences and if the problem persist provides an example project to reproduce it?

**Comment by dweldon** [comment]
Sorry about that - it must have been something specific to my development environment. Package updates fixed the issue for me.
