### ISSUE TITLE
Broken width after opening component with router

### ISSUE THREAD

**Issue by goodmind** [gvaldambrini/storybook-router#15]
If you open component with router and then open another component in Storybook, width of page becomes smaller each time you open component with router decorator

**Comment by gvaldambrini** [comment]
Hi @goodmind, thanks for the report. Could you please provide more details? Which version are you using? With react or vue? Do you have some snippet or an example project to help me reproducing the problem? Thanks!

**Comment by goodmind** [comment]
@gvaldambrini it's react, but now I think its not related to this module. I removed it and have same issue. I'll make minimal reproduce though

**Comment by goodmind** [comment]
i think this `div` in `_innerComponent` breaks my `height: 100%` flexbox layout

**Comment by goodmind** [comment]
@gvaldambrini https://github.com/gvaldambrini/storybook-router/blob/715d35677ed823155c5c25c90161f24d76981d1a/src/react.js#L18

**Comment by gvaldambrini** [comment]
I'm not sure why the wrapping div causes the problem you mention, but as it is not really needed I removed it and pushed a bugfix version without it (0.3.2). Please check if this solves your issue and if not provide an example to reproduce the problem.
