### ISSUE TITLE
Vue component beforeRouteEnter guard doesn't get called

### ISSUE THREAD

**Issue by ianwalter** [gvaldambrini/storybook-router#21]
Issue:

### Which version are you using?

^0.3.2

### Are you using storybook-router with a react based project or a vue one?

Vue

### Please describe the problem:

A components `beforeRouteEnter` guard doesn't seem to be called before the component is created but it should.

### Please explain how to reproduce the issue or (better) provide an example to do it.

Add a `beforeRouteEnter` method with a `console.log` to a component. Navigate to the component. See that nothing is logged to the console.

Side suggestion: Update to vue-router v3.

**Comment by gvaldambrini** [comment]
Inspired by [this codepen](https://codepen.io/patrickodacre/pen/owjVNK) I added [an example](https://github.com/gvaldambrini/storybook-router/blob/master/examples/vue-router/Navigation.js#L173) that uses `beforeRouteEnter` and everything seems to work so I'm not able to reproduce the issue. Can you please provide more details?

**Comment by ianwalter** [comment]
@gvaldambrini Thanks for checking this out so quickly.

Yes, your example works. It looks like the issue I'm running into is that the `beforeRouteEnter` does not get fired as expected on the default route initially. So if you change the `/bar` route in your example to be the default route `/` then `beforeRouteEnter` doesn't get called (when you click on the story in the Storybook sidebar). If you click on the story, then click on the `foo` link then click on the `bar` link it does get fired, but obviously that is not ideal.

**Comment by ianwalter** [comment]
Yes, works as expected. Must have been a caching/HMR issue. Thanks for the help and sorry for the noise.
