### ISSUE TITLE
transpilation broken with the latest release

### ISSUE THREAD

**Issue by travi** [gvaldambrini/storybook-router#3]
its not obvious to me what changed with the build, but the latest build appears to no longer transpile to the degree that it used to. it now [leaves es module `import` syntax](https://travis-ci.org/travi/admin.travi.org-components/builds/237701161) in the bundle that is set to `main` in the `package.json`. 

it probably does make sense to include a version that uses es modules like this, but it would need to be defined as `module` in the `package.json` rather than `main` in order for webpack to handle it correctly.

i [use rollup in my projects](https://github.com/travi/admin.travi.org-components/blob/master/rollup.config.js) to easily produce a common-js bundle and an es-module bundle that i define as `main` and `module`, respectively.

**Comment by gvaldambrini** [comment]
You're right, for not obvious reason the transpilation was broken (just for the module part). The new version (0.2.5) contains a small fix to the .babelrc config file that should fix the problem (or at least works in the test environment I'm using). Can you please confirm that?

**Comment by travi** [comment]
looks like that took care of it. thanks so much for the quick resolution!
