### ISSUE TITLE
Support for props in Vue router

### ISSUE THREAD

**Issue by pr1moz** [gvaldambrini/storybook-router#31]
### Which version are you using?
1.0.2
### Are you using storybook-router with a react based project or a vue one?
Vue
### Please describe the problem:
Passing `props` to a component through Vue router doesn't work in Storybook.
### Please explain how to reproduce the issue or (better) provide an example to do it.
You can use the same example as in Vue router documentation for passing props - https://router.vuejs.org/guide/essentials/passing-props.html

In my case I'm using function mode, like so:
```
.addDecorator(StoryRouter({}, {
  routes: [{
    name: 'wizard',
    path: '/wizard/:id/:step',
    component: Wizard,
    props: route => {
      return {
        id: parseInt(route.params.id),
        step: parseInt(route.params.step),
      };
    },
  }],
}))
```

Using this, `props` are not sent to Wizard component when the story is opened.

**Comment by gvaldambrini** [comment]
Hi @pr1moz,
I'm sorry but I cannot reproduce the problem.

I expanded the router examples to pass properties to the wrapped component [here](https://github.com/gvaldambrini/storybook-router/blob/master/examples/vue-router/Navigation.js#L48) and it works as expected. 
Moreover, if you have a look at the [implementation](https://github.com/gvaldambrini/storybook-router/blob/master/packages/vue/vue.js#L10) you can see the all the props passed to StoryRouter are passed as is to the wrapped VueRouter, so it shouldn't be any difference in that sense.
Am I missing something? Thanks!

**Comment by gvaldambrini** [comment]
Hi @pr1moz, any news on this?

**Comment by pr1moz** [comment]
@gvaldambrini Sorry, didn't get a notification that you responded. We ended up dropping `props` in the actual implementation and passed it through `vuex`, so we didn't need it in the storybook.

Closing.
