### ISSUE TITLE
Story Source displaying `StoryRouter` source, not real story source

### ISSUE THREAD

**Issue by mdespuits** [gvaldambrini/storybook-router#38]
Issue:

## Which version are you using?

* `storybook-react-router`: `^5.0.2`
* `@storybook/react`: `^5.0.6`

## Are you using storybook-router with a react based project or a vue one?

React

## Please describe the problem:

It's working, but once I add the `StoryRouter()` decorator, the Story Source only displays the StoryRouter's component definition:

```jsx
<StoryRouter story={anonymous} links={null} routerProps={null} />
```

## Please explain how to reproduce the issue or (better) provide an example to do it.

```jsx
import StoryRouter from 'storybook-react-router';

const story = storiesOf('Tabs', module);
story.addDecorator(StoryRouter());
story.add('Example Hidden', () => <h1>Will not show source</h1>, {
  info: { inline: true, source: true },
});
```

**Comment by gvaldambrini** [comment]
As far as I know this is a common problem with every HOC, and a solution does not exists. Maybe using React Hooks can solve the problem, but I'm not sure that would be a good idea in the foreseeable future.

**Comment by mdespuits** [comment]
From what I understand, there is a way if your correctly pass refs, but using the decorator globally instead of on a per-story basis seemed to resolve the problem for now.
