### ISSUE TITLE
Fixed version of @storybook/react

### ISSUE THREAD

**Issue by ndelangen** [gvaldambrini/storybook-router#4]
https://github.com/gvaldambrini/storybook-router/blob/master/package.json#L28

Hey any reason why you've locked the version of @storybook/react to exactly `3.0.0`?

Any updates on our part and this addon will be duplicating the @storybook/react package.. Which is a bad idea 😯

**Comment by gvaldambrini** [comment]
Just a leftover, thanks 👍
