### ISSUE TITLE
Preserve default storybook hot reloading

### ISSUE THREAD

**Issue by lsirivong** [gvaldambrini/storybook-router#6]
Is it possible to retain the hot reloading set up in storybook while using this decorator?

From my initial tests, it seems like `shouldComponentUpdate` is preventing the stories from hot reloading.

I've created an example repo here:
https://github.com/lsirivong/storybook-router-hot-reload-test

**Comment by gvaldambrini** [comment]
Thanks for the example, I'll have a look asap.

**Comment by gvaldambrini** [comment]
Fixed in 0.2.8
